// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6OP1sgwP-F0aVPQws3-9sNVZwOJ-yEek',
    appId: '1:307984038481:web:8c439bd81fcd7477141670',
    messagingSenderId: '307984038481',
    projectId: 'scrubrapp-b0e6f',
    authDomain: 'scrubrapp-b0e6f.firebaseapp.com',
    storageBucket: 'scrubrapp-b0e6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPR9Ik-cfBcetndk_7Xy4jFuEUuiPm7QM',
    appId: '1:307984038481:android:a88a720ecbbc6174141670',
    messagingSenderId: '307984038481',
    projectId: 'scrubrapp-b0e6f',
    storageBucket: 'scrubrapp-b0e6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPzn0IIPKZRzkZktnvcouthFEnYfNV9XI',
    appId: '1:307984038481:ios:c92d48a210a40c27141670',
    messagingSenderId: '307984038481',
    projectId: 'scrubrapp-b0e6f',
    storageBucket: 'scrubrapp-b0e6f.appspot.com',
    androidClientId: '307984038481-5kqjl2p7gfoskjolgepshg46obos98q2.apps.googleusercontent.com',
    iosClientId: '307984038481-j7aaqgvd1eqoe1hprde9fo8e0praola4.apps.googleusercontent.com',
    iosBundleId: 'com.example.scrubrClientApp',
  );
}
